### ISSUE TITLE
VirtualAlloc hooking reports anomaly

### ISSUE THREAD

**Issue by simonides** [apriorit/mhook#1]
On Win10 hooking VirtualAlloc gives the following error message/ warning: `[0x7FFEF0CADFE0] ANOMALY: meaningless REX prefix used` 

The function after the skiped jumps:
[https://pastebin.com/RRaQ8JG0](https://pastebin.com/RRaQ8JG0)

This doesn't happen on Win7 (I'd have to get back to you with the dissasemble on that if you need it). The hook works but I am not sure if I can simply ignore that or I have to "fix" that in some way in the library. Can you tell me why this is bad? [http://wiki.osdev.org/X86-64_Instruction_Encoding#REX_prefix](http://wiki.osdev.org/X86-64_Instruction_Encoding#REX_prefix) This site lists it as a legacy opcode. Can you clarify this please?

**Comment by Grivus** [comment]
@simonides, could you please post your kernel32.dll version and winver output (cmd->winver->line with version info)? 

I have tried to run mhook-test on Win10 and met no ANOMALY in log, but my byte-code of VirtualAlloc is different from yours one.

**Comment by simonides** [comment]
@Grivus Thank you for taking a look. The file version is 10.0.16299.15 . Date modified: 29.9.2017 15:42
[kernel32.zip](https://github.com/apriorit/mhook/files/1563121/kernel32.zip)
Winver output: Version 1709 (OS Build 16299.125)

**Comment by simonides** [comment]
This is how it looks on Win7(Build 7601:SP1): https://pastebin.com/MVt16n2z
File version: 6.1.7601.23714
[kernel32.zip](https://github.com/apriorit/mhook/files/1563145/kernel32.zip)

**Comment by Grivus** [comment]
@simonides, ok, I think I figured it out.

The REX prefix consists of only four meaningful bits, and all that bits are zero in the opcode 0x40 - first part of the 
00007FFEF0CADFE0 40 53                push        rbx   
command. So mhook think that while it is legal opcode there is no sense to write it, because it change nothing from assembler point of view.

But Windows has it's own rules, and like described [here](https://stackoverflow.com/questions/30698761/how-should-the-byte-sequence-0x40-0x55-be-interpreted-by-an-x86-64-emulator) it want all instructions to be at least 2 bytes long to allow us insert some jump instead of it if needed. So Windows compilers insert empty REX into small-size commands to reach needed length. 

So you can just ignore that message. I think we could remove it to not confuse users.

**Comment by simonides** [comment]
Thank you for clarifying!

**Comment by SergiusTheBest** [comment]
I'll leave this issue open until we remove that message.
